baseURL: https://Katock-Cricket.github.io/MyBlog
languageCode: en-us
title: 蝈蝈影视公司
theme: "PaperMod"
ShowToc: true
TocOpen: true
post_asset_folder: true
params:
    # ShowShareButtons: true
    # ShowReadingTime: true
    # ShowBreadCrumbs: true
    # comments: true
    homeInfoParams:
        Title: 蝈蝈影视公司官方博客
        Content: "随便搞点没用的"

    #  SsocialIcons: # optional
    #     - name: "<platform>"
    #         url: "<link>"
    #     - name: "<platform 2>"
    #         url: "<link2>"

    outputs:
        home:
            - HTML
            - RSS
            - JSON # is necessary

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    
    cover:
        responsiveImages: true
        linkFullImages: true

