baseURL: https://Katock-Cricket.github.io/MyBlog
languageCode: en-us
title: 蝈蝈影视公司官方
theme: "PaperMod"
cover:
    image: "https://i.ibb.co/K0HVPBd/paper-mod-profilemode.png/url"
    # can also paste direct link from external site
    # ex. https://i.ibb.co/K0HVPBd/paper-mod-profilemode.png
    alt: "<alt text>"
    caption: "<text>"
    relative: false # To use relative path for cover image, used in hugo Page-bundles

params:
    ShowShareButtons: true
    homeInfoParams:
        Title: 这里是蝈蝈影视公司的博客
        Content: 什么都没有别看了

    #  SsocialIcons: # optional
    #     - name: "<platform>"
    #         url: "<link>"
    #     - name: "<platform 2>"
    #         url: "<link2>"

    outputs:
        home:
            - HTML
            - RSS
            - JSON # is necessary

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    
    cover:
        responsiveImages: false
        linkFullImages: true

